### You are given a space separated list of numbers.Your task is to print a reversed NumPy array with the element type float.

In [26]:
#import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    li=list(map(float,arr))
    li.reverse()
    return numpy.array(li)
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

4 5 6 7 8 9 10 11 12
[12. 11. 10.  9.  8.  7.  6.  5.  4.]


### You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [27]:
n=list(map(int,input().split(" ")))
print(numpy.reshape(numpy.array(n),(3,3)))

2 4 6 8 9 7 5 3 10
[[ 2  4  6]
 [ 8  9  7]
 [ 5  3 10]]


### You are given a X integer array matrix with space separated elements ( = rows and  = columns). Your task is to print the transpose and flatten results.

In [39]:
n,m=list(map(int, input().split(" ")))
li=[]
for i in range(n):
    li.append(list(map(int, input().split(" "))))
print(numpy.transpose(numpy.array(li)))
print(numpy.array(li).flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### You are given two integer arrays of size NXP and MXP ( N&M  are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

In [75]:
n,m,p=list(map(int, input().split(" ")))
li=[]
for i in range(n+m):
    li.append(list(map(int, input().split(" "))))
print(numpy.array(li))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### ZEROS and Ones

In [2]:
import  numpy
N = tuple(map(int, input().split()))

                
print(numpy.zeros(N, dtype = numpy.int))
print(numpy.ones(N, dtype = numpy.int))

2 2 3
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


### Eye and Identity

In [3]:

numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

2 6
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]]


### Array Mathematics

In [4]:
n,m=map(int, input().split(" "))
arr1=[]
for i in range(n):
    arr1.append(list(map(int, input().split(" "))))
arr1=numpy.array(arr1)

arr2=[]
for i in range(n):
    arr2.append(list(map(int, input().split(" "))))
arr2=numpy.array(arr2)
print(numpy.add(arr1,arr2))
print(numpy.subtract(arr1,arr2))
print(numpy.multiply(arr1,arr2))
print(arr1//arr2)
print(numpy.mod(arr1,arr2))
print(numpy.power(arr1,arr2))

1 4
2 4 8 16
1 2 3 4
[[ 3  6 11 20]]
[[ 1  2  5 12]]
[[ 2  8 24 64]]
[[2 2 2 4]]
[[0 0 2 0]]
[[    2    16   512 65536]]


### Floor, Ceil, Rint

In [5]:
arr=numpy.array(list(map(float, input().split())))
numpy.set_printoptions(legacy='1.13')
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

2.2 4.4 5.5 6.6 7.7 8.8
[ 2.  4.  5.  6.  7.  8.]
[ 3.  5.  6.  7.  8.  9.]
[ 2.  4.  6.  7.  8.  9.]


### Sum and Prod

In [6]:
n,m=map(int, input().split())
arr=[]
for i in range(n):
    arr.append(list(map(int, input().split())))
arr-numpy.array(arr)

print(numpy.prod(numpy.sum(arr, axis=0)))

2 2
1 2
4 8
50


### Min and Max

In [7]:
n,m=map(int, input().split())
a=[]
for i in range(n):
    a.append(list(map(int, input().split())))
a=numpy.array(a)
print(numpy.max(numpy.min(a, axis=1)))

2 4
2 2 4 4
4 4 5 8
4


### Mean, Var, Std

In [8]:
n,m=map(int, input().split())
a=[]
for i in range(n):
    a.append(list(map(int, input().split())))
a=numpy.array(a)
print(numpy.mean(a, axis=1))
print(numpy.var(a, axis=0))
print(round(numpy.std(a),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### Dot and Cross

In [12]:
n=int(input())
a=[]
for i in range(n):
    a.append(list(map(int, input().split())))
b=[]
for i in range(n):
    b.append(list(map(int, input().split())))
mul=[]
for col in range(n):
    li=[]
    for row in range(n):
        t=0
        for k in range(n):
            t+=a[col][k]*b[k][row]
        li.append(t)
    mul.append(li)
print(numpy.array(mul))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### Inner and Outer

### Polynomials

In [13]:
poly = [float(x) for x in input().split()]
x = float(input())

print(numpy.polyval(poly, x))

1.1 2 3
0
3.0


In [14]:
A=numpy.array(list(map(int, input().split())))
B=numpy.array(list(map(int, input().split())))
print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


### Linear Algebra

In [15]:
n=int(input())
a=[]
for i in range(n):
    a.append(list(map(float, input().split())))
print(round(numpy.linalg.det(a),2))

2
1.1 1.1
1.1 1.1
0.0
